# Generated by Django 5.0.14 on 2026-09-18 12:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('workout_type', models.CharField(choices=[('gym', 'Strength & Weights'), ('cardio', 'Cardio & Running'), ('hiit', 'HIIT & Circuit'), ('calisthenics', 'Calisthenics & Bodyweight'), ('mobility', 'Mobility & Stretching'), ('sports', 'Sports & Swimming'), ('walk', 'Walking & Steps'), ('rest', 'Rest & Recovery')], default='gym', max_length=30)),
                ('title', models.CharField(help_text='e.g. Chest & Triceps, 5k Pace Run', max_length=120)),
                ('duration_mins', models.PositiveIntegerField(default=45, help_text='Duration in minutes')),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('intensity', models.CharField(choices=[('low', 'Low / Recovery'), ('moderate', 'Moderate'), ('high', 'High Intensity'), ('max', 'Max Effort / PR')], default='moderate', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Sets, reps, distances or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BodyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kilograms', max_digits=5, null=True)),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, help_text='Body fat percentage', max_digits=4, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=1, help_text='Waist circumference in cm', max_digits=5, null=True)),
                ('water_liters', models.DecimalField(blank=True, decimal_places=2, help_text='Water intake in liters', max_digits=4, null=True)),
                ('sleep_hours', models.DecimalField(blank=True, decimal_places=1, help_text='Sleep in hours', max_digits=4, null=True)),
                ('energy_level', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, help_text='1 (Low) to 5 (High)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
