# Generated by Django 5.0.14 on 2026-09-18 13:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutlog',
            name='split_type',
            field=models.CharField(choices=[('push', 'Push (Chest, Shoulders, Triceps)'), ('pull', 'Pull (Back, Biceps, Rear Delts)'), ('legs', 'Legs (Quads, Hamstrings, Calves)'), ('core', 'Core & Abs'), ('full', 'Full Body Strength'), ('other', 'Cardio / Other')], default='push', help_text='Push, Pull, Legs, Core', max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutlog',
            name='title',
            field=models.CharField(help_text='e.g. Chest & Triceps, Heavy Squat Day', max_length=120),
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(help_text='e.g. Barbell Bench Press, Incline DB Press', max_length=100)),
                ('set_number', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, help_text='Weight in kg (0 for bodyweight)', max_digits=6)),
                ('reps', models.PositiveIntegerField(default=10, help_text='Number of completed repetitions')),
                ('is_warmup', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_sets', to='body.workoutlog')),
            ],
            options={
                'ordering': ['exercise_name', 'set_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast 🌅'), ('lunch', 'Lunch ☀️'), ('dinner', 'Dinner 🌙'), ('snack', 'Snack / Drink 🍎')], default='lunch', max_length=20)),
                ('food_name', models.CharField(help_text='e.g. Oats with banana, Chicken breast & rice', max_length=150)),
                ('calories', models.PositiveIntegerField(help_text='Estimated calories in kcal')),
                ('protein_g', models.DecimalField(blank=True, decimal_places=1, help_text='Optional protein in grams', max_digits=5, null=True)),
                ('is_healthy_choice', models.BooleanField(default=True, help_text='Includes veg/fruit/whole foods')),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
