# Generated by Django 5.0.14 on 2026-09-18 12:24

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Me', help_text='Your display name in this ledger', max_length=50)),
                ('partner_name', models.CharField(default='Partner', help_text='Partner / roommate display name', max_length=50)),
                ('currency_symbol', models.CharField(default='£', max_length=5)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_ledger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Costco run, Electricity bill, Dinner', max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('groceries', '🛒 Groceries & Food'), ('rent', '🏠 Rent & Housing'), ('utilities', '⚡ Bills & Utilities'), ('dining', '🍽️ Dining & Takeaway'), ('transport', '🚗 Transport & Fuel'), ('entertainment', '🍿 Leisure & Fun'), ('home', '🛋️ Home & Supplies'), ('health', '💊 Health & Pharmacy'), ('other', '📦 Miscellaneous')], default='groceries', max_length=30)),
                ('paid_by', models.CharField(choices=[('user', 'User (Me)'), ('partner', 'Partner')], default='user', max_length=20)),
                ('split_type', models.CharField(choices=[('50_50', 'Split Equally (50 / 50)'), ('user_full', '100% Mine (Personal)'), ('partner_full', '100% Partner')], default='50_50', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='finance.financeledger')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
