# Generated by Django 5.0.14 on 2026-09-18 13:01

import django.db.models.deletion
import django.utils.timezone
import finance.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financeledger',
            name='user',
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Our Household', max_length=100)),
                ('currency_symbol', models.CharField(default='£', max_length=5)),
                ('monthly_savings_goal', models.DecimalField(decimal_places=2, default=Decimal('500.00'), max_digits=10)),
                ('invite_code', models.CharField(default=finance.models.generate_invite_code, max_length=16, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_households', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='households', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('income', '🟢 Money In (Earned)'), ('expense', '🔴 Money Out (Spent)')], default='expense', max_length=10)),
                ('title', models.CharField(help_text='What was this? e.g. Rakesh Monthly Salary, Tesco Groceries', max_length=160)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(choices=[('salary', '💼 Primary Salary'), ('freelance', '💻 Freelance & Side Hustle'), ('business', '📈 Business & Sales'), ('bonus', '🎁 Bonus & Gifts'), ('investments', '📊 Dividends & Returns'), ('income_other', '💰 Other Income'), ('groceries', '🛒 Groceries & Supermarket'), ('housing', '🏠 Rent / Mortgage'), ('utilities', '⚡ Bills & Utilities (Energy, Water, Wifi)'), ('dining', '🍽️ Dining Out & Takeaways'), ('transport', '🚗 Transport & Fuel / Commute'), ('shopping', '🛍️ Shopping & Clothes'), ('entertainment', '🍿 Fun & Subscriptions (Netflix, etc.)'), ('health', '💊 Health & Fitness'), ('kids', '👶 Kids & Family'), ('travel', '✈️ Holidays & Trips'), ('expense_other', '📦 Miscellaneous Spent')], default='groceries', max_length=40)),
                ('person_tag', models.CharField(default='Joint', help_text='Who was this for/from? e.g. Husband, Wife, Joint', max_length=60)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.household')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='FinanceLedger',
        ),
    ]
