# Generated by Django 5.0.14 on 2026-06-22 19:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_project'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bible_memory_goal',
            field=models.IntegerField(default=500),
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('category', models.CharField(default='unassigned', max_length=100)),
                ('hook', models.TextField(blank=True, default='')),
                ('context', models.TextField(blank=True, default='')),
                ('ease_factor', models.FloatField(default=2.5)),
                ('interval_days', models.IntegerField(default=0)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('mastered', models.BooleanField(default=False)),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_verses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'reference'],
            },
        ),
    ]
