# Generated by Django 5.0.14 on 2026-06-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_userprofile_bible_memory_goal_bibleverse'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibleverse',
            name='practice_type',
            field=models.CharField(choices=[('bible', 'Bible'), ('english', 'English')], default='bible', max_length=20),
        ),
    ]
