# Generated by Django 5.0.14 on 2026-06-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_bibleverse_practice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bible_memory_goal',
            field=models.IntegerField(default=1),
        ),
    ]
