# Generated by Django 5.0.14 on 2026-06-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_userprofile_bible_memory_goal'),
    ]

    operations = [
        migrations.RunSQL(
            sql="UPDATE dashboard_userprofile SET bible_memory_goal = 1 WHERE bible_memory_goal = 500;",
            reverse_sql="UPDATE dashboard_userprofile SET bible_memory_goal = 500 WHERE bible_memory_goal = 1;",
        ),
    ]
