# Generated by Django 5.0.14 on 2026-06-25 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_reset_goal_to_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.TextField(blank=True, help_text='What is the task / context')),
                ('definition', models.TextField(blank=True, help_text='How does task completion look like')),
                ('steps', models.TextField(blank=True, help_text='Steps to achieve the task')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('todo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='dashboard.todo')),
            ],
        ),
    ]
