# Generated by Django 5.0.14 on 2026-06-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_taskbreakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskbreakdown',
            name='challenges',
            field=models.TextField(blank=True, help_text='Challenges you might face'),
        ),
    ]
