# Generated by Django 5.0.14 on 2026-07-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_add_challenges_to_task_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='focus_log',
            field=models.TextField(blank=True, default=''),
        ),
    ]
