# Generated by Django 5.0.14 on 2026-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_aiusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pomodorosession',
            name='total_paused_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
