# Generated by Django 5.0.14 on 2026-07-20 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_pomodorosession_ended_at_pomodorosession_is_paused_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.todo'),
        ),
    ]
