# Generated by Django 5.0.14 on 2026-07-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_pomodorosession_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('stop_todo', '⛔ Stop-Do / Say No'), ('urgent_important', 'Urgent & Important'), ('important_not_urgent', 'Important & Not Urgent'), ('urgent_not_important', 'Urgent & Not Important'), ('neither', 'Neither (Urgent/Important)')], default='unassigned', max_length=30),
        ),
    ]
