# Generated by Django 5.0.14 on 2026-07-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomodorosession',
            name='category',
            field=models.CharField(choices=[('phd', 'PhD Work'), ('other', 'Other Work')], default='other', max_length=20),
        ),
    ]
