# Generated by Django 5.0.14 on 2026-08-05 08:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_pomodorosession_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time_slot', models.CharField(help_text='Format HH:MM e.g. 10:15', max_length=5)),
                ('raw_text', models.CharField(help_text="User's typed description or code", max_length=255)),
                ('category', models.CharField(choices=[('research', 'Research / Reading'), ('coding', 'Coding / Building'), ('admin', 'Admin / Email / Planning'), ('meeting', 'Meeting / Call'), ('distraction', 'Distraction / Social Media'), ('break', 'Break / Lunch / Resting'), ('other', 'Other')], default='other', max_length=20)),
                ('source', models.CharField(default='desktop', help_text='desktop, web, mobile', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time_slot'],
                'unique_together': {('user', 'date', 'time_slot')},
            },
        ),
    ]
