# Generated by Django 5.0.14 on 2026-08-05 13:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_timeauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeauditlog',
            name='category',
            field=models.CharField(choices=[('phd', 'PhD'), ('projects', 'Side Projects'), ('life_skills', 'Life Skills'), ('spiritual', 'Spiritual'), ('cooking', 'Cooking'), ('driving', 'Driving'), ('distracted', 'Distracted'), ('break', 'Break'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='HabitProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Take Isabgol, Night Reflection', max_length=150)),
                ('category', models.CharField(choices=[('phd', 'PhD'), ('projects', 'Side Projects'), ('life_skills', 'Life Skills'), ('spiritual', 'Spiritual'), ('cooking', 'Cooking'), ('driving', 'Driving'), ('distracted', 'Distracted'), ('break', 'Break'), ('other', 'Other')], default='life_skills', max_length=20)),
                ('target_time', models.CharField(blank=True, default='', help_text='Target slot e.g. 11:30 or 22:00', max_length=5)),
                ('keywords', models.CharField(blank=True, default='', help_text='Comma-separated keywords for auto-matching in 15-min logs e.g. isabgol, fibre', max_length=255)),
                ('icon', models.CharField(default='⚡', help_text='Icon symbol', max_length=10)),
                ('streak_count', models.IntegerField(default=0)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_protocols', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_time', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HabitProtocolLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='manual', help_text='manual, audit_log_auto', max_length=30)),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.habitprotocol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-completed_at'],
                'unique_together': {('protocol', 'date')},
            },
        ),
    ]
