# Generated by Django 5.0.14 on 2026-08-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_timeauditlog_category_habitprotocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitprotocol',
            name='frequency',
            field=models.CharField(choices=[('everyday', 'Every day'), ('weekdays', 'Weekdays (Mon-Fri)'), ('weekends', 'Weekends (Sat-Sun)'), ('once', 'Once')], default='everyday', max_length=20),
        ),
    ]
