# Generated by Django 5.0.14 on 2026-08-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_habitprotocol_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitprotocol',
            name='category',
            field=models.CharField(choices=[('phd', 'PhD'), ('projects', 'Side Projects'), ('life_skills', 'Life Skills'), ('spiritual', 'Spiritual'), ('cooking', 'Cooking'), ('driving', 'Driving'), ('exercise', 'Exercise'), ('getting_ready', 'Getting Ready'), ('distracted', 'Distracted'), ('break', 'Break'), ('other', 'Other')], default='life_skills', max_length=20),
        ),
        migrations.AlterField(
            model_name='timeauditlog',
            name='category',
            field=models.CharField(choices=[('phd', 'PhD'), ('projects', 'Side Projects'), ('life_skills', 'Life Skills'), ('spiritual', 'Spiritual'), ('cooking', 'Cooking'), ('driving', 'Driving'), ('exercise', 'Exercise'), ('getting_ready', 'Getting Ready'), ('distracted', 'Distracted'), ('break', 'Break'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
