# Generated by Django 5.0.14 on 2026-06-11 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=150)),
                ('definition', models.TextField()),
                ('example', models.TextField(blank=True, null=True)),
                ('difficulty', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3)),
                ('last_reviewed', models.DateTimeField(blank=True, null=True)),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('review_count', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('interval_days', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
